"""Versioned Cruise product and runtime contracts."""

PACKAGE_VERSION = "0.1.0"
PRODUCT_MATURITY = "research-baseline"

COMPATIBILITY_SCHEMA_VERSION = 2
RUNTIME_CONFIG_SCHEMA_VERSION = 1
PYTHON_CONTRACT_VERSION = 3
SIDECAR_PROTOCOL_VERSION = 6
SIDECAR_REQUEST_BYTES = 136
SIDECAR_RESPONSE_BYTES = 352
HOST_UDF_ABI_VERSION = 2
HOST_UDF_INPUTS = 8
HOST_UDF_OUTPUTS = 2
DECODER_ABI_VERSION = 1
DECODER_INPUTS = 9
DECODER_OUTPUTS = 4
