#pragma once

#define CRUISE_SIDECAR_PROTOCOL_VERSION 4
#define CRUISE_SIDECAR_REQUEST_BYTES 128
#define CRUISE_SIDECAR_RESPONSE_BYTES 352

#define CRUISE_EPOCH_PREPARED 0
#define CRUISE_EPOCH_EXECUTING 1
#define CRUISE_EPOCH_COMMITTED 2
